### ISSUE TITLE
UI: Snip Modal Buttons Text

### ISSUE THREAD

**Issue by cdrani** [cdrani/chorus#19]
![image](https://github.com/cdrani/chorus/assets/18746599/c2e82cc9-fbd6-44b2-91f3-b1342b453dbc)

The text does not seem to be vertically centered. Same issue with the slider left and right text.

**Comment by faizi-7** [comment]
Please assign it to me

**Comment by cdrani** [comment]
@faizi-7: Assigned. Let me know if you need help with setup or on the PR.

**Comment by cdrani** [comment]
Up for grabs by anyone now.
