### ISSUE TITLE
Discography doesnt work on one group.

### ISSUE THREAD

**Issue by bonelifer** [cdrani/chorus#203]
**Describe the bug**
Can't do a discography of Steppenwolf for some reason. Works on other artists.

**To Reproduce**
Go to their page, try the discography button.

**Expected behavior**
Should work.

**Desktop (please complete the following information):**
 - OS: Xubuntu 22.04
 - Browser: Firefox and Chromium
 - Version 121/120.0.6099.71

**Smartphone (please complete the following information):**

**Additional context**

**Comment by cdrani** [comment]
Thanks for raising this up. I have found the cause and will issue a release later today. 👍
