### ISSUE TITLE
[BUG]: Extension not working on Windows 

### ISSUE THREAD

**Issue by cdrani** [cdrani/chorus#217]
Error caused by hardcoded relative path to icon image. This path string is of unix format, thus only supports macos & linux, not windows. Instead we should use [chrome.runtime.getURL](https://developer.chrome.com/docs/extensions/reference/api/runtime#method-getURL) which will resolve the path style based on the browser os.

https://github.com/cdrani/chorus/blob/9225d619f73f9e34fb53a4e04eaf63f3c94d3ab2/src/popup/index.js#L111

**Comment by sstephanyy** [comment]
@cdrani: I can be doing something wrong, but I tried to replace this line of code 
`cover.src = '../icons/logo.png' `

With this:
`cover.src = chrome.runtime.getURL('icons/logo.png');`
And this:
`cover.src = chrome.runtime.getURL('../icons/logo.png');`

But with no sucess...
![image](https://github.com/cdrani/chorus/assets/128330097/bab9211b-44a9-4453-bd15-793cb75fa9fd)

Did you test this chrome.runtime.getURL on your Windows? Did it solve?

**Comment by cdrani** [comment]
@sstephanyy: It should be `cover.src = chrome.runtime.getURL('../icons/logo.png')`. It should be the relative path.

I can confirm on my end again.

**Comment by cdrani** [comment]
@sstephanyy: Okay. Chased down the issue. My previous successes on windows were a false positive. I would run `pnpm watch` to create the dist folder on mac, which I would then share with windows, load the extension  and it would work as expected. This was a quick shortcut as the windows instance was not dev ready - no nodejs, git, package installer, etc.

However, investigation further, I setup the a full environment to try replicate your case. I setup the environment, cloned the repo, installed the dependencies, and encountered exact errors (hopefully). There was an error in the console about not being able to load certain files.

![image](https://github.com/cdrani/chorus/assets/18746599/50c3faf0-ac36-4208-b484-bdb0ddd49dfa)

When I looked in the `dist` folder, there was no `chunks` folder, whereas in mac there was one. This was the difference b/t mac and windows. The chunk folder contains the main bundled logic for setting up the ui in a Spotify tab, such as the settings modal plus the additional playback buttons. Additionally, the popup get its ui data from the tab, for ex. the missing cover image, and track name, artists, etc.

Anyways, the actual solution should be the below changes to the `rollup.config.js` file. I guess we have to explicitly add the chunkFileNames key or else the chunk files are not created in windows? 🤷 

```diff
+ import path from 'path'
import { chromeExtension, simpleReloader } from 'rollup-plugin-chrome-extension'

export default {
    input: 'src/manifest.chrome.json',
    output: {
        dir: 'dist',
        format: 'esm',
+       chunkFileNames: path.join('chunks','[name]-[hash].js'),
-        // sourcemap: true
    },
    plugins: [chromeExtension(), simpleReloader()]
}
```

You know what's crazy? We would have never caught this error. I don't use windows and the builds for releases are either built locally on my mac or github action ubuntu instance.

Fingers crossed this is the actual fix. 🙏

**Comment by sstephanyy** [comment]
@cdrani: You are a GENIUS! It worked 🙏. I will make a pull request to add these changes :)

You have so much knowledge and are so good at resolving bugs. At first, I thought I needed to replace [name]-[hash].js with specific values manually. 😅


![image](https://github.com/cdrani/chorus/assets/128330097/0f262c6d-de64-478f-b69b-b5963ca809ea)

**Comment by sstephanyy** [comment]
Oh nooooooooooo. Actually, my joy was short-lived.  I was using the extension for a few minutes and suddenly, everything broked again :/
![image](https://github.com/cdrani/chorus/assets/128330097/73625850-c0c1-4855-b9a6-5672c17fbd92)

**Comment by cdrani** [comment]
Whooo! We live and we learn. We learn and we live. Glad this resolved this issue.

> Hey, off-topic now, but what do u think to add a feature to download .mp3 of your favourite section of a track?

A user asked something similar in support. It's not at the top of my queue, but I am not against it.
