### ISSUE TITLE
Add Feature to Download .mp3 of Favorite Section of a Track

### ISSUE THREAD

**Issue by sstephanyy** [cdrani/chorus#219]
**Is your feature request related to a problem? Please describe.**
Currently, users of the Chorus extension have the ability to save their favorite sections of a track within the application. However, there is no functionality available to **download these saved sections as .mp3 files** for offline listening or to share it in others social media.

**Describe the solution you'd like**
I propose adding a new feature to the Chorus extension that allows users to download their favorite track sections as .mp3 files. This feature **would enhance the user experience** by providing a convenient way to access and listen to their saved sections in anywhere they want.

**How would work?**
- Implement a download button or option for each saved track section.
- When the user clicks on the download button, the corresponding track section should be converted to .mp3 format and downloaded to their device.
- Ensure that the downloaded .mp3 files are of high quality and accurately represent the saved track sections.

**Comment by cdrani** [comment]
Great idea. I had similar thoughts, but this would conflict with Spotify TOS. Perhaps in a separate branch that is not ever released? Don't have time currently to implement. Closing for now.
