### ISSUE TITLE
Settings Icon in Now Playing Widget Should Display Aria Label on Hover

### ISSUE THREAD

**Issue by cdrani** [cdrani/chorus#30]
**Describe the bug**
Settings Icon in Now Playing Widget Should Display Aria Label on Hover. Other icons display an tooltip with their element's aria label and we should follow the lead.

**Expected behavior**
Hovering over the Settings Icon should display a tooltip displaying a 'Edit Snip' aria label. This is quite similar to the implementation on the track list.

**Screenshots**

**CURRENT**

![Screenshot 2023-07-27 at 21 11 35](https://github.com/cdrani/chorus/assets/18746599/3ded62d9-3eed-480c-b8a3-9b6da376f347)

**EXPECTED** (based on tracklist implementation)

![image](https://github.com/cdrani/chorus/assets/18746599/747d5452-08db-4820-a69c-7ab0a455671b)

**IMPLEMENTATION**

Based on the tracklist implementation, it should be as simple as adding the `role` and `aria-label` attributes to the Icon component? Reference https://github.com/cdrani/chorus/blob/ef998b9e084bf8174d94359ffe5f8f7474113ade/models/snip-icon.js#L23-L25

**Comment by Piyush-Deshmukh** [comment]
Hey there, can you please tell in which file the Settings Icon is present ?

**Comment by cdrani** [comment]
@Piyush-Deshmukh: https://github.com/cdrani/chorus/blob/5c88d09d3f4608712fe861e66435e8f3fbac49eb/models/icon.js#L14
