### ISSUE TITLE
[BUG]: Update #chorus-controls Style Properties

### ISSUE THREAD

**Issue by cdrani** [cdrani/chorus#98]
### **Describe the bug**

Currently using a dashed border around the chorus controls modal. Time for a change perhaps?
<img width="340" alt="image" src="https://github.com/cdrani/chorus/assets/18746599/796a76d9-799c-4979-a8aa-b3189f39f7f0">

### **Expected behavior**

Possible New border styles. These are starting points, but use your eyes to feel it out and make it look good.
1. maybe a 6px border radius, 3px width, ridge
2. maybe a solid border, 3px width, optional border-radius of 6, 8, or 10 px
3. Open to other possibilities, but would prefer not to use dashed or dotted

### **Additional context**

Location of #chorus-controls styles. Combine the two blocks into a single #chorus-controls block.

https://github.com/cdrani/chorus/blob/4e8e7d53aab754753ef93b1c8aa11b8b7a4a0c4a/src/styles.css#L46-L57

**Comment by ahmohil** [comment]
I want to work on this kindly assign this issue to me
