### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by cdrani** [cdrani/chorus#99]
### **Describe the bug**

The `manifest.json` file has now been moved out of the root project folder and separated into chrome/manifest.json and firefox/manifest.json files. This change is now resulting in the below issue with shields.io badge:

<img width="848" alt="image" src="https://github.com/cdrani/chorus/assets/18746599/f6683623-fdef-496f-907d-8f758b65a558">

### **Expected behavior**

The version badge should display the current version of the latest release. Currently it's 1.6.1? Anyways, the shields badge url should be changed to reference the manifest.json in the `firefox` directory. It should be as simple as including the [`filename`](https://shields.io/badges/git-hub-manifest-version-path) query param to the shields route. You can test it on the shields.io site before applying it to the README.

### **Additional context**

While referencing the link above, I would welcome updates to the colour of the other labels. A majority of them are some variant of green, but I would love to see some bright blues, pinks, purples, etc. Maybe update the style as well, but they all badges in the README would need to be update to the new style for uniformity.

Here's the particular line to focus on: https://github.com/cdrani/chorus/blob/4e8e7d53aab754753ef93b1c8aa11b8b7a4a0c4a/README.md?plain=1#L10

**Comment by kasai2210** [comment]
Hi, I just a PR against this bug, kindly review and merge it.
